<?php

namespace Zahar\SportBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ExerciseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExerciseRepository extends EntityRepository
{
    public function getAllExercisesByPeriod($period)
    {
        return $this;
    }
}
